### PR TITLE
use ENV for secret keys

### PR DESCRIPTION
**Pull request by tilsammans**
Hard-coding secret keys in configuration files isn't good practice.

This pull request assumes the secrets are present in ENV instead. People who are not using ENV can still hard-code them in the file if they want.

### CODE REVIEW

**Comment by tf** [comment]
I'd be open to taking this route. Originally, the template used hard coded strings to leave the dotenv/secrets.yml decision to the user. But probably using env is a more sane default.

* There one line using `env` instead of `ENV` causing the build to fail.
* I wonder if we should `ENV.fetch` in order to fail loudly if something is missing.
* The comment stating that hard coding is bad practice should be rephrased.
* Could you remove the whitespace fixes from the commit? No idea, why whitespace is so messed up in the README, but fixing it should not be part of this change i guess.

**Comment by tilsammans** [comment]
No problem. I will build on this PR and we can continue to discuss! Thanks for your consideration.

**Comment by tf** [comment]
I'll close this for now due to inactivity. Feel free to re-open any time. I still think this is a good idea.

**Comment by tilsammans** [comment]
I opened up #306 since commits don't show up for a closed PR.

I agree with using fetch, this makes the requirement very clear. I am not sure what you'd like to see differently in the README, it's clear to me, but feel free to comment on it and I will use your copy.

**Pull request closed without merging**
