### PR TITLE
Cannot use ruby 2.2.x

### PR DESCRIPTION
**Pull request by tilsammans**
Because of ActiveAdmin.

### CODE REVIEW

**Comment by tf** [comment]
Hi,

thank for the PR. The linked issue seems to refer to Rails 3.2 compatibility with Ruby 2.2. Pageflow uses Rails 4 though. Is ActiveAdmin known to be incompatible with Ruby 2.2?

**Comment by tilsammans** [comment]
Yes. I had Ruby 2.2.2 and got that exact same error.

After switching to 2.1.6 the error in ActiveAdmin went away.

**Comment by tf** [comment]
Ah ok. Just out of curiosity: What was the error message?

**Comment by g-w** [comment]
Maybe we should also change the lower bound to 2.0.0? This reflects the end of life of ruby 1.9.3. See https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by tilsammans** [comment]
The error message is:

```
undefined method `reorder' for nil:NilClass
```

I would recommend against changing the lower bounds to Ruby 2.0.0. I know 1.9.3 is EOL but my patch is concerned about Pageflow just not working at all, and not about policies regarding version numbers.

**Comment by tf** [comment]
I agree. Long as we are running Pageflow instances with Ruby 1.9.3 ourselves, we can keep it in the support matrix.

**Pull request merged**
