### PR TITLE
[WIP] Ruby 2.5.0

### PR DESCRIPTION
**Pull request by tilsammans**
I am mostly curious if it will just work without changes. Let Travis find that out.

This one accidentally also contains my typo fixes.

I can pull those loose if they don't get merged earlier.

### CODE REVIEW

**Comment by tf** [comment]
Interesting, indeed. No idea, though, what those errors mean or where they could come from.

**Comment by tilsammans** [comment]
Travis only started supporting 2.5.0 proper since yesterday.

Need to add a `gem update --system` first, then it should work.

**Comment by tilsammans** [comment]
Currently stuck because of the Devise syntax error. See https://mensfeld.pl/2017/12/ruby-2-5-0-upgrade-remarks/

It's fixed in devise 4.4.0 but that opens a huge can of worms, since we're currently on 3.5. :'(

**Comment by tf** [comment]
see #1031

**Pull request closed without merging**
