### PR TITLE
Show new entry button only to publisher or above

### PR DESCRIPTION
**Pull request by aviav**

### CODE REVIEW

**Comment by tf** [comment]
Test

**Comment by tf** [comment]
Test 2

**Comment by tf** [comment]
I'll test this in Dedicated.

**Comment by aviav** [comment]
I just pushed a fix

**Comment by tf** [comment]
Needs to be Ruby 2.1 compatible.

**Comment by aviav** [comment]
I see. For how long do we support Ruby 2.1, anyway? It does not even receive security fixes anymore

https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/

**Comment by tf** [comment]
Not decided yet. We can discuss dropping it in the next major version.

**Comment by tf** [comment]
see #847

**Pull request closed without merging**
